<?xml version="1.0"?>
<robot name="jetbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- 尺寸定義 -->
<!-- 參數定義 -->
<xacro:property name="wheel_radius" value="0.0325"/>  <!-- 對應 wheel_link_radius -->
<xacro:property name="wheel_thickness" value="0.025"/>  <!-- 對應 wheel_link_length -->
<xacro:property name="wheel_distance" value="0.175"/>  <!-- 左右輪距 = 2 × 0.0875 -->
<xacro:property name="wheel_x_offset" value="0.05"/>  <!-- 輪子前後位置 -->

<xacro:property name="body_link_x_dim" value="0.20"/>
<xacro:property name="body_link_y_dim" value="0.15"/>
<xacro:property name="body_link_z_dim" value="0.005"/>
<xacro:property name="wheel_link_radius" value="0.0325"/>
<xacro:property name="wheel_link_length" value="0.025"/>
<xacro:property name="wheel_link_z_location" value="${-body_link_z_dim/2}"/>
<xacro:property name="caster_link_radius" value="0.04"/>
<xacro:property name="caster_link_z_location" value="${-body_link_z_dim/2-wheel_link_radius+caster_link_radius}"/>
<xacro:property name="camera_radius" value="0.0025"/>
<xacro:property name="camera_baseline" value="0.16"/>
<xacro:property name="camera_height_from_body" value="0.155"/>
<xacro:property name="camera_offset_from_front" value="0.005"/>
<xacro:property name="body_density" value="500.0"/>
<xacro:property name="wheel_density" value="1000.0"/>
<xacro:property name="caster_density" value="1000.0"/>
<xacro:property name="pi_constant" value="3.14159265"/>
<xacro:property name="body_mass" value="${body_density*body_link_x_dim*body_link_y_dim*body_link_z_dim}"/>
<xacro:property name="wheel_mass" value="${wheel_density*pi_constant*wheel_link_radius*wheel_link_radius*wheel_link_length}"/>
<xacro:property name="caster_mass" value="${caster_density*4.0/3.0*pi_constant*caster_link_radius*caster_link_radius*caster_link_radius}"/>
<xacro:property name="Iz_wheel" value="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}"/>
<xacro:property name="I_wheel" value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}"/>
<xacro:property name="I_caster" value="${(2.0/5.0)*caster_mass*caster_link_radius*caster_link_radius}"/>

<xacro:macro name="inertia_wheel">
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" 
                 iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}"/>
    </inertial>
</xacro:macro>

<xacro:macro name="inertia_caster">
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${caster_mass}"/>
        <inertia ixx="${I_caster}" ixy="0.0" ixz="0.0" 
                 iyy="${I_caster}" iyz="0" izz="${I_caster}"/>
    </inertial>
</xacro:macro>

<material name="blue">
    <color rgba="0.2 0.4 0.8 1"/>
</material>
<material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
</material>
<material name="red">
    <color rgba="1 0 0 0.8"/>
</material>
<material name="green">
    <color rgba="0 1 0 0.8"/>
</material>
<material name="gray">
    <color rgba="0.5 0.5 0.5 1"/>
</material>
<material name="silver">
    <color rgba="0.7 0.7 0.7 1"/>
</material>

<link name="base_footprint"/>

<joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="body_link"/>
    <origin xyz="0 0 ${wheel_link_radius}" rpy="0 0 0"/>
</joint>

<link name="body_link">
    <visual>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="blue"/>
    </visual>
    
    <collision>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass}"/>
        <inertia
            ixx="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_z_dim*body_link_z_dim)}" ixy="0"
            iyy="${(1/12)*body_mass*(body_link_x_dim*body_link_x_dim+body_link_z_dim*body_link_z_dim)}" ixz="0"
            izz="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_x_dim*body_link_x_dim)}" iyz="0"/>
    </inertial>
</link>

<joint name="base_link_joint" type="fixed">
    <parent link="body_link"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<link name="base_link"/>

<!-- 左輪 -->
<link name="left_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>  <!-- link 內設為 0 -->
        <material name="black">
            <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>  <!-- link 內設為 0 -->
    </collision>
    <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001"/>
    </inertial>
</link>

<!-- 右輪 -->
<link name="right_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>  <!-- link 內設為 0 -->
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>  <!-- link 內設為 0 -->
    </collision>
    <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001"/>
    </inertial>
</link>

<!-- 輪子關節 - 用你喜歡的格式 -->
<joint name="left_wheel_joint" type="continuous">
    <parent link="body_link"/>
    <child link="left_wheel"/>
    <origin xyz="${wheel_x_offset} ${wheel_distance/2} 0" rpy="0 0 0"/>
    <!-- X=0.05, Y=0.0875, Z=0 -->
    <axis xyz="0 1 0"/>
</joint>

<joint name="right_wheel_joint" type="continuous">
    <parent link="body_link"/>
    <child link="right_wheel"/>
    <origin xyz="${wheel_x_offset} ${-wheel_distance/2} 0" rpy="0 0 0"/>
    <!-- X=0.05, Y=-0.0875, Z=0 -->
    <axis xyz="0 1 0"/>
</joint>ㄋ

<joint name="caster_joint" type="fixed">
    <parent link="body_link"/>
    <child link="caster_link"/>
    <origin xyz="${-body_link_x_dim/2 + 0.02} 0 ${caster_link_z_location}" rpy="0 0 0"/>
</joint>

<link name="caster_link">
    <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <sphere radius="${caster_link_radius}"/>
        </geometry>
        <material name="silver"/>
    </visual>
    
    <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <sphere radius="${caster_link_radius}"/>
        </geometry>
    </collision>
    
    <xacro:inertia_caster/>
</link>

<joint name="camera_pole_joint" type="fixed">
    <parent link="body_link"/>
    <child link="camera_pole_link"/>
    <origin xyz="${body_link_x_dim/2 - camera_offset_from_front} 0 ${body_link_z_dim/2}" rpy="0 0 0"/>
</joint>

<link name="camera_pole_link">
    <visual>
        <origin xyz="0 0 ${camera_height_from_body/2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="0.005" length="${camera_height_from_body}"/>
        </geometry>
        <material name="gray"/>
    </visual>
</link>

<joint name="camera_mount_joint" type="fixed">
    <parent link="camera_pole_link"/>
    <child link="camera_mount_link"/>
    <origin xyz="0 0 ${camera_height_from_body}" rpy="0 0 0"/>
</joint>

<link name="camera_mount_link">
    <visual>
        <geometry>
            <box size="0.01 ${camera_baseline + 0.01} 0.01"/>
        </geometry>
        <material name="gray"/>
    </visual>
</link>

<joint name="camera_left_joint" type="fixed">
    <parent link="camera_mount_link"/>
    <child link="camera_left_link"/>
    <origin xyz="0 ${camera_baseline/2} 0" rpy="0 0 0"/>
</joint>

<link name="camera_left_link">
    <visual>
        <geometry>
            <cylinder radius="${camera_radius}" length="0.01"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="red"/>
    </visual>
</link>

<joint name="camera_left_optical_joint" type="fixed">
    <parent link="camera_left_link"/>
    <child link="camera_left_optical_frame"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
</joint>

<link name="camera_left_optical_frame"/>

<joint name="camera_right_joint" type="fixed">
    <parent link="camera_mount_link"/>
    <child link="camera_right_link"/>
    <origin xyz="0 ${-camera_baseline/2} 0" rpy="0 0 0"/>
</joint>

<link name="camera_right_link">
    <visual>
        <geometry>
            <cylinder radius="${camera_radius}" length="0.01"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="green"/>
    </visual>
</link>

<joint name="camera_right_optical_joint" type="fixed">
    <parent link="camera_right_link"/>
    <child link="camera_right_optical_frame"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
</joint>

<link name="camera_right_optical_frame"/>

</robot>